# Generated by Django 3.1.14 on 2023-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Activity',
            field=models.BooleanField(default=False, verbose_name='Активировать/Деактивировать пользователя'),
        ),
    ]
