# Generated by Django 3.1.14 on 2023-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230407_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Дата рождения'),
        ),
    ]
