# Generated by Django 4.1.7 on 2023-04-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление'),
        ),
    ]
