version: '3.8'
services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  media_volume:
  static_volume: