version: '3.8'
services:
  web:
    container_name: practice
    build: .
    ports:
      - "7776:7776"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              gunicorn settings.wsgi:application -b :7776"

volumes:
  media_volume:
  static_volume: