version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: "practice"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"