# Generated by Django 3.1.14 on 2023-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_directions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
