# Generated by Django 4.1.7 on 2023-04-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20230408_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание направление',
                'verbose_name_plural': 'Описания направления',
            },
        ),
        migrations.CreateModel(
            name='TitleMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='h1')),
                ('main_title', models.CharField(max_length=200, verbose_name='div')),
            ],
            options={
                'verbose_name': 'Информация на сайте',
                'verbose_name_plural': 'Информация на сайте',
            },
        ),
        migrations.RemoveField(
            model_name='directions',
            name='city',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='desc_wtd',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='what_to_do',
        ),
        migrations.AlterField(
            model_name='directions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='desc_lang_direct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.directionsdesc', verbose_name='Описание направления'),
        ),
    ]
