# Generated by Django 4.1.7 on 2023-04-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20230408_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
