# Generated by Django 4.1.7 on 2023-04-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_titlemain_main_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'Описание направление', 'verbose_name_plural': 'Описание направление'},
        ),
        migrations.AlterModelOptions(
            name='directionsdesc',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направление'},
        ),
    ]
