# Generated by Django 4.1.7 on 2023-04-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_alter_directions_id'),
        ('internship', '0008_remove_directions_desc_lang_direct'),
    ]

    operations = [
    ]
