# Generated by Django 3.1.14 on 2023-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=200000, verbose_name='Текст статьи'),
        ),
    ]
