# Generated by Django 4.1.7 on 2023-04-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0005_remove_quiz_difficluty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
    ]
